### ISSUE TITLE
Todo for next release

### ISSUE THREAD

**Issue by bouteillerAlan** [bouteillerAlan/archupdate#63]
- [x] set cmd for update in setting #64 
- [x] remove check for konsole & checkupdate since all that is set in the settings (#62)
- [x] merge #61 
- [x] update version in the metadata
- [x] pack
- [x] tag
- [x] release github
- [x] release pling
- [x] release aur

FYI : I plan to do that this weekend 30/31 march.

**Comment by sikmike** [comment]
Please add the option to run custom commands after the update (and / or visually signal in the terminal that the update process is finished).
Great work by the way ;)

**Comment by bouteillerAlan** [comment]
> Please add the option to run custom commands after the update (and / or visually signal in the terminal that the update process is finished). Great work by the way ;)

With the update cmd now in the settings (for the next release), this is done I think ^^ 
![image](https://github.com/bouteillerAlan/archupdate/assets/30547569/2a382e0e-06d2-4dae-af23-0f5c90f43e8a)
